"""add column savad_books

Revision ID: fb3925f3c1bd
Revises: 2c5a1f22f46e
Create Date: 2025-09-19 12:42:15.448055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3925f3c1bd'
down_revision: Union[str, Sequence[str], None] = '2c5a1f22f46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saved_books', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'saved_books')
    # ### end Alembic commands ###
